<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Converts the chat conversation primary key from auto-increment integer to UUID.
 *
 * Drops and recreates the three related tables in the correct order so that
 * foreign-key constraints are always satisfied. Existing chat data is lost
 * (acceptable: the feature was brand-new).
 *
 * After this migration:
 *   conversations.id          → uuid  (generated by Eloquent HasUuids)
 *   conversation_user.conversation_id → uuid FK
 *   messages.conversation_id          → uuid FK
 *   messages.type enum also includes 'image' and 'file' (added here so a
 *   separate migration is not needed).
 */
return new class extends Migration
{
    public function up(): void
    {
        // ── 1. Drop dependants first ─────────────────────────────────
        Schema::dropIfExists('messages');
        Schema::dropIfExists('conversation_user');
        Schema::dropIfExists('conversations');

        // ── 2. Conversations (UUID primary key) ──────────────────────
        Schema::create('conversations', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->enum('type', ['direct', 'channel'])->default('direct');
            $table->string('name')->nullable();
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('last_message_at')->nullable();
            $table->timestamps();

            $table->index('last_message_at');
        });

        // ── 3. Pivot table (UUID FK) ─────────────────────────────────
        Schema::create('conversation_user', function (Blueprint $table) {
            $table->id();
            $table->uuid('conversation_id');
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->timestamp('last_read_at')->nullable();
            $table->timestamps();

            $table->foreign('conversation_id')
                  ->references('id')->on('conversations')
                  ->cascadeOnDelete();

            $table->unique(['conversation_id', 'user_id']);
            $table->index('user_id');
        });

        // ── 4. Messages (UUID FK for conversation_id; int PK for polling cursor) ─
        Schema::create('messages', function (Blueprint $table) {
            $table->id();                                // integer PK — used as ?after= poll cursor
            $table->uuid('conversation_id');
            $table->foreignId('sender_id')->constrained('users')->cascadeOnDelete();

            $table->text('ciphertext');                  // sealed to recipient
            $table->text('ciphertext_self')->nullable(); // sealed to sender
            $table->enum('encryption', ['sealed', 'none'])->default('sealed');
            $table->enum('type', ['text', 'location', 'mission', 'image', 'file'])->default('text');

            $table->timestamps();

            $table->foreign('conversation_id')
                  ->references('id')->on('conversations')
                  ->cascadeOnDelete();

            $table->index(['conversation_id', 'id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('messages');
        Schema::dropIfExists('conversation_user');
        Schema::dropIfExists('conversations');
    }
};
